### ISSUE TITLE
Modifiers Not Working

### ISSUE THREAD

**Issue by PauloAlmas** [arramus/Snufkin-Community-Pack-Server-Side-Vehicles-A19-Stable-2020Nov21#1]
Vehicles Modifiers Not Working
Is not possible to put mods in veicles, why ?

Vehicles Mods are workin in fine :

Vanila Vehicles
Bdubs Vehicles
...

**Comment by arramus** [comment]
I tested one vehicle modifier mod called Toad_VehicleMods. Here are the results.

They could be added to the slots in the vehicle.
![20201205020145_1](https://user-images.githubusercontent.com/71211641/101193046-53e2bb00-369f-11eb-87d6-bc729f55ea77.jpg)

The light modifier does have an impact on the light brightness.
![20201205020135_1](https://user-images.githubusercontent.com/71211641/101193201-92787580-369f-11eb-98e9-c0992a02099b.jpg)

In fact, it reduces the light brightness for this vehicle. Here is the normal brightness without the mod.
![20201205020155_1](https://user-images.githubusercontent.com/71211641/101193306-ba67d900-369f-11eb-96b1-2509ecc497eb.jpg)

For some vehicles like the motorcycle the modifiers will work because their lights are very low.
![20201205020823_1](https://user-images.githubusercontent.com/71211641/101193380-d79ca780-369f-11eb-9711-63671e014adb.jpg)

And with the modifier. So sometimes it works and sometimes it doesn't because the vehicle is already set higher than the modifier.
![20201205020808_1](https://user-images.githubusercontent.com/71211641/101193412-e3886980-369f-11eb-8ee3-bcbf3dac59f4.jpg)

Running some vehicle modifiers can cause issues with other mods because they change IDs and may cause conflicts. It all depends on the mix of mods.

**Comment by PauloAlmas** [comment]
my problem is i cant see that Modifiers slots :( you can see them ? maybe a conflict with other mod

where i can get that veicle with eagle ?

**Comment by arramus** [comment]
I also tested War3zuk Vehicle Revamp. Both mods could run together.

It was actually very good.

No Mod.
![20201205083719_1](https://user-images.githubusercontent.com/71211641/101225683-6bd53180-36d5-11eb-91fa-932ef13ef1a5.jpg)

With light mod.
![20201205083732_1](https://user-images.githubusercontent.com/71211641/101225697-742d6c80-36d5-11eb-9e3b-604f86968522.jpg)

And both War3zuk and Toad's vehicle mods together.
![20201205083644_1](https://user-images.githubusercontent.com/71211641/101225713-81e2f200-36d5-11eb-9e72-bfcaff7625a4.jpg)

The code in this mod is the same as for vanilla vehicles for mod slots.

items.xml		
<passive_effect name="ModSlots" operation="base_set" value="4"/>

It's unfortunate to have this issue and maybe a conflict with another mod.

**Comment by PauloAlmas** [comment]
hooo tanks

i will see that 2 mods i dint know :) about those addons

**Comment by PauloAlmas** [comment]
Is possible to Ride a Giant Bunny or Brear or vulture ? Or make a zombie ride them ?

Where can i see all the  textures of 7dtd ? to put in zombies

**Comment by PauloAlmas** [comment]
I found the BUG, you trie 

press F6
Spawn
ATV
press E /see no modifeiers

**Comment by arramus** [comment]
Vehicles which cannot take the vehicle mods are:

Armored Car
ATV
Jet Pack
Parachute
Whirligig

There was a reason for this in the early release based on adding 'tags' to vehicles to ensure the attachments were accepted on dedicated servers. However, a new method was found and these are not really necessary anymore. These 'tags' stop the vehicles taking modifiers. These are all original Snufkin vehicles from the original build except the Whirligig which was based on a Snufkin vehicle.

The vehicles were never intended to use modifiers until they were released in A20 as they were already buffed.

However, I am just consulting with the modding team to allow these vehicles to accept modifiers. If acceptable and they cause no issues, they will be in the next update.

**Comment by PauloAlmas** [comment]
Ok tanks for informations 👍 
and for you help

**Comment by arramus** [comment]
Here is an update with all vehicles accepting vehicle modifiers.
https://github.com/arramus/Snufkin-CommunityPack-ServerSideVehicles-A19-2020Dec05

The ATV.
![20201205232040_1](https://user-images.githubusercontent.com/71211641/101247730-7556ac00-375e-11eb-94f4-20e8b9a329f9.jpg)

While all vehicles can accept vehicle modifiers, they will only function as well as they are compatible.

This update also added some localisation to show seating capacity for each vehicle and removed custom containers which are causing too many conflicts with other mods. This gives all vehicles a default storage capacity based on its class.

**Comment by PauloAlmas** [comment]
Hooo many tanks,

eatch time it gets beter and beter 🥇
